// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
const spec_Identifier = {__proto__:null,True:8, False:10, def:12, if:14, elif:16, else:18, return:20, raise:22, global:24, nonlocal:26}
export const parser = LRParser.deserialize({
  version: 14,
  states: "!pQYQPOOO!WQPO'#CmO!_QPO'#CpOOQO'#Cu'#CuOOQO'#Cq'#CqQYQPOOOOQO,59X,59XO!fQPO,59XOOQO,59[,59[O!mQPO,59[OOQO-E6o-E6oOOQO1G.s1G.sOOQO1G.v1G.v",
  stateData: "!t~OhOSPOS~ORROSROTROUROVROWROXROYROZRO[RO]RO^RO`POcQO~O_UO~PYObWO~PYO_ZO~PYOb[O~PYO",
  goto: "!ZjPPPPPPPPPPPPPPPPPkPPksPPP!R]ROPQTVXQTOQVPQXQVYTVX]SOPQTVX",
  nodeNames: "⚠ LineComment Program Identifier True False def if elif else return raise global nonlocal String ) ( Application ] [ Application",
  maxTerm: 25,
  nodeProps: [
    ["openedBy", 15,"(",18,"["],
    ["closedBy", 16,")",19,"]"]
  ],
  skippedNodes: [0,1],
  repeatNodeCount: 1,
  tokenData: "%b~R^XY}YZ}]^}pq}rs!`xy#|yz$R!P!Q$W!Q![$u!c!}$u!}#O%W#P#Q%]#R#S$u#T#o$u~!SSh~XY}YZ}]^}pq}~!cVOr!`rs!xs#O!`#O#P!}#P;'S!`;'S;=`#v<%lO!`~!}O^~~#QRO;'S!`;'S;=`#Z;=`O!`~#^WOr!`rs!xs#O!`#O#P!}#P;'S!`;'S;=`#v;=`<%l!`<%lO!`~#yP;=`<%l!`~$RO`~~$WO_~~$ZP!P!Q$^~$cSP~OY$^Z;'S$^;'S;=`$o<%lO$^~$rP;=`<%l$^~$zSR~!Q![$u!c!}$u#R#S$u#T#o$u~%]Oc~~%bOb~",
  tokenizers: [0],
  topRules: {"Program":[0,2]},
  specialized: [{term: 3, get: value => spec_Identifier[value] || -1}],
  tokenPrec: 0
})

