// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
const spec_Identifier = {__proto__:null,True:8, False:10, def:12, if:14, elif:16, else:18, return:20, raise:22, lambda:24, global:26, nonlocal:28}
export const parser = LRParser.deserialize({
  version: 14,
  states: "!pQYQPOOO!ZQPO'#CnO!bQPO'#CqOOQO'#Cv'#CvOOQO'#Cr'#CrQYQPOOOOQO,59Y,59YO!iQPO,59YOOQO,59],59]O!pQPO,59]OOQO-E6p-E6pOOQO1G.t1G.tOOQO1G.w1G.w",
  stateData: "!w~OiOSPOS~ORROSROTROUROVROWROXROYROZRO[RO]RO^RO_ROaPOdQO~O`UO~PYOcWO~PYO`ZO~PYOc[O~PYO",
  goto: "![kPPPPPPPPPPPPPPPPPPlPPltPPP!S]ROPQTVXQTOQVPQXQVYTVX]SOPQTVX",
  nodeNames: "⚠ LineComment Program Identifier True False def if elif else return raise lambda global nonlocal String ) ( Application ] [ Application",
  maxTerm: 26,
  nodeProps: [
    ["openedBy", 16,"(",19,"["],
    ["closedBy", 17,")",20,"]"]
  ],
  skippedNodes: [0,1],
  repeatNodeCount: 1,
  tokenData: "%b~R^XY}YZ}]^}pq}rs!`xy#|yz$R!P!Q$W!Q![$u!c!}$u!}#O%W#P#Q%]#R#S$u#T#o$u~!SSi~XY}YZ}]^}pq}~!cVOr!`rs!xs#O!`#O#P!}#P;'S!`;'S;=`#v<%lO!`~!}O_~~#QRO;'S!`;'S;=`#Z;=`O!`~#^WOr!`rs!xs#O!`#O#P!}#P;'S!`;'S;=`#v;=`<%l!`<%lO!`~#yP;=`<%l!`~$ROa~~$WO`~~$ZP!P!Q$^~$cSP~OY$^Z;'S$^;'S;=`$o<%lO$^~$rP;=`<%l$^~$zSR~!Q![$u!c!}$u#R#S$u#T#o$u~%]Od~~%bOc~",
  tokenizers: [0],
  topRules: {"Program":[0,2]},
  specialized: [{term: 3, get: (value) => spec_Identifier[value] || -1}],
  tokenPrec: 0
})

