// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
const spec_Identifier = {__proto__:null,True:8, False:10, def:12, if:14, elif:16, else:18, return:20, raise:22}
export const parser = LRParser.deserialize({
  version: 14,
  states: "!pQYQPOOO!QQPO'#CkO!XQPO'#CnOOQO'#Cs'#CsOOQO'#Co'#CoQYQPOOOOQO,59V,59VO!`QPO,59VOOQO,59Y,59YO!gQPO,59YOOQO-E6m-E6mOOQO1G.q1G.qOOQO1G.t1G.t",
  stateData: "!n~OfOSPOS~ORROSROTROUROVROWROXROYROZRO[RO^POaQO~O]UO~PYO`WO~PYO]ZO~PYO`[O~PYO",
  goto: "!XhPPPPPPPPPPPPPPPiPPiqPPP!P]ROPQTVXQTOQVPQXQVYTVX]SOPQTVX",
  nodeNames: "⚠ LineComment Program Identifier True False def if elif else return raise String ) ( Application ] [ Application",
  maxTerm: 23,
  nodeProps: [
    ["openedBy", 13,"(",16,"["],
    ["closedBy", 14,")",17,"]"]
  ],
  skippedNodes: [0,1],
  repeatNodeCount: 1,
  tokenData: "%b~R^XY}YZ}]^}pq}rs!`xy#|yz$R!P!Q$W!Q![$u!c!}$u!}#O%W#P#Q%]#R#S$u#T#o$u~!SSf~XY}YZ}]^}pq}~!cVOr!`rs!xs#O!`#O#P!}#P;'S!`;'S;=`#v<%lO!`~!}O[~~#QRO;'S!`;'S;=`#Z;=`O!`~#^WOr!`rs!xs#O!`#O#P!}#P;'S!`;'S;=`#v;=`<%l!`<%lO!`~#yP;=`<%l!`~$RO^~~$WO]~~$ZP!P!Q$^~$cSP~OY$^Z;'S$^;'S;=`$o<%lO$^~$rP;=`<%l$^~$zSR~!Q![$u!c!}$u#R#S$u#T#o$u~%]Oa~~%bO`~",
  tokenizers: [0],
  topRules: {"Program":[0,2]},
  specialized: [{term: 3, get: value => spec_Identifier[value] || -1}],
  tokenPrec: 0
})

