// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
export const parser = LRParser.deserialize({
  version: 14,
  states: "!pQYQPOOOkQPO'#CdOrQPO'#CgOOQO'#Cl'#ClOOQO'#Ch'#ChQYQPOOOOQO,59O,59OOyQPO,59OOOQO,59R,59RO!QQPO,59ROOQO-E6f-E6fOOQO1G.j1G.jOOQO1G.m1G.m",
  stateData: "!X~O_OSPOS~ORROSROTROVPOYQO~OUUO~PYOXWO~PYOUZO~PYOX[O~PYO",
  goto: "!QaPPPPPPPPbPPbjPPPx]ROPQTVXQTOQVPQXQVYTVX]SOPQTVX",
  nodeNames: "⚠ LineComment Program Identifier String Boolean ) ( Application ] [ Application",
  maxTerm: 16,
  nodeProps: [
    ["openedBy", 6,"(",9,"["],
    ["closedBy", 7,")",10,"]"]
  ],
  skippedNodes: [0,1],
  repeatNodeCount: 1,
  tokenData: "%m~R_XY!QYZ!Q]^!Qpq!Qrs!cst$Pxy$_yz$d!Q![$i!]!^$z!c!}$i!}#O%c#P#Q%h#R#S$i#T#o$i~!VS_~XY!QYZ!Q]^!Qpq!Q~!fVOr!crs!{s#O!c#O#P#Q#P;'S!c;'S;=`#y<%lO!c~#QOS~~#TRO;'S!c;'S;=`#^;=`O!c~#aWOr!crs!{s#O!c#O#P#Q#P;'S!c;'S;=`#y;=`<%l!c<%lO!c~#|P;=`<%l!c~$SQ#Y#Z$Y#h#i$Y~$_OT~~$dOV~~$iOU~~$nSR~!Q![$i!c!}$i#R#S$i#T#o$i~%PSP~OY$zZ;'S$z;'S;=`%]<%lO$z~%`P;=`<%l$z~%hOY~~%mOX~",
  tokenizers: [0],
  topRules: {"Program":[0,2]},
  tokenPrec: 0
})

