// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
const spec_Identifier = {__proto__:null,deffun:8, defvar:10, "set!":12, if:14, let:16, cond:18, else:20, begin:22, lambda:24}
export const parser = LRParser.deserialize({
  version: 14,
  states: "!pQYQPOOO!WQPO'#CmO!_QPO'#CpOOQO'#Cu'#CuOOQO'#Cq'#CqQYQPOOOOQO,59X,59XO!fQPO,59XOOQO,59[,59[O!mQPO,59[OOQO-E6o-E6oOOQO1G.s1G.sOOQO1G.v1G.v",
  stateData: "!t~OhOSPOS~ORROSROTROUROVROWROXROYROZRO[RO]RO^RO`POcQO~O_UO~PYObWO~PYO_ZO~PYOb[O~PYO",
  goto: "!ZjPPPPPPPPPPPPPPPPPkPPksPPP!R]ROPQTVXQTOQVPQXQVYTVX]SOPQTVX",
  nodeNames: "⚠ LineComment Program Identifier deffun defvar set! if let cond else begin lambda String Boolean ) ( Application ] [ Application",
  maxTerm: 25,
  nodeProps: [
    ["openedBy", 15,"(",18,"["],
    ["closedBy", 16,")",19,"]"]
  ],
  skippedNodes: [0,1],
  repeatNodeCount: 1,
  tokenData: "&P~RbXY!ZYZ!Z]^!Zpq!Zqr!lrs#Wst$txy%Syz%X}!O!l!Q![!l!]!^%^!a!b!l!c!}!l!}#O%u#P#Q%z#R#S!l#T#o!l~!`Sh~XY!ZYZ!Z]^!Zpq!Z~!qVR~qr!l}!O!l!Q![!l!a!b!l!c!}!l#R#S!l#T#o!l~#ZVOr#Wrs#ps#O#W#O#P#u#P;'S#W;'S;=`$n<%lO#W~#uO]~~#xRO;'S#W;'S;=`$R;=`O#W~$UWOr#Wrs#ps#O#W#O#P#u#P;'S#W;'S;=`$n;=`<%l#W<%lO#W~$qP;=`<%l#W~$wQ#Y#Z$}#h#i$}~%SO^~~%XO`~~%^O_~~%cSP~OY%^Z;'S%^;'S;=`%o<%lO%^~%rP;=`<%l%^~%zOc~~&POb~",
  tokenizers: [0],
  topRules: {"Program":[0,2]},
  specialized: [{term: 3, get: value => spec_Identifier[value] || -1}],
  tokenPrec: 0
})

