// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
const spec_Identifier = {__proto__:null,deffun:8, defvar:10, "set!":12, if:14, let:16, cond:18, else:20, begin:22, lambda:24, "λ":26}
export const parser = LRParser.deserialize({
  version: 14,
  states: "!pQYQPOOO!ZQPO'#CnO!bQPO'#CqOOQO'#Cv'#CvOOQO'#Cr'#CrQYQPOOOOQO,59Y,59YO!iQPO,59YOOQO,59],59]O!pQPO,59]OOQO-E6p-E6pOOQO1G.t1G.tOOQO1G.w1G.w",
  stateData: "!w~OiOSPOS~ORROSROTROUROVROWROXROYROZRO[RO]RO^RO_ROaPOdQO~O`UO~PYOcWO~PYO`ZO~PYOc[O~PYO",
  goto: "![kPPPPPPPPPPPPPPPPPPlPPltPPP!S]ROPQTVXQTOQVPQXQVYTVX]SOPQTVX",
  nodeNames: "⚠ LineComment Program Identifier deffun defvar set! if let cond else begin lambda λ String Boolean ) ( Application ] [ Application",
  maxTerm: 26,
  nodeProps: [
    ["openedBy", 16,"(",19,"["],
    ["closedBy", 17,")",20,"]"]
  ],
  skippedNodes: [0,1],
  repeatNodeCount: 1,
  tokenData: "&P~RbXY!ZYZ!Z]^!Zpq!Zqr!lrs#Wst$txy%Syz%X}!O!l!Q![!l!]!^%^!a!b!l!c!}!l!}#O%u#P#Q%z#R#S!l#T#o!l~!`Si~XY!ZYZ!Z]^!Zpq!Z~!qVR~qr!l}!O!l!Q![!l!a!b!l!c!}!l#R#S!l#T#o!l~#ZVOr#Wrs#ps#O#W#O#P#u#P;'S#W;'S;=`$n<%lO#W~#uO^~~#xRO;'S#W;'S;=`$R;=`O#W~$UWOr#Wrs#ps#O#W#O#P#u#P;'S#W;'S;=`$n;=`<%l#W<%lO#W~$qP;=`<%l#W~$wQ#Y#Z$}#h#i$}~%SO_~~%XOa~~%^O`~~%cSP~OY%^Z;'S%^;'S;=`%o<%lO%^~%rP;=`<%l%^~%zOd~~&POc~",
  tokenizers: [0],
  topRules: {"Program":[0,2]},
  specialized: [{term: 3, get: (value) => spec_Identifier[value] || -1}],
  tokenPrec: 0
})

