// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Stacker from "./Stacker.bs.js";
import * as CodeEditor from "./CodeEditor.bs.js";

function Main(props) {
  var match = React.useState(function () {
        return "";
      });
  var program = match[0];
  var match$1 = React.useState(function () {
        return /* Editing */0;
      });
  return React.createElement("div", undefined, React.createElement("div", {
                  id: "program-source"
                }, React.createElement(CodeEditor.make, {
                      program: program,
                      setProgram: match[1],
                      editable: match$1[0] === /* Editing */0
                    })), React.createElement("div", {
                  id: "stacker"
                }, React.createElement(Stacker.make, {
                      program: program
                    })));
}

var make = Main;

export {
  make ,
}
/* react Not a pure module */
